# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Section.create(id:1, has_checkbox:false, number:'3_1', question:'Including Actual Miles', directions:'') 
Section.create(id:2, has_checkbox:false, number:'3_2', question:'Not Including Actual Miles', directions:'') 
Section.create(id:3, has_checkbox:false, number:'4', question:'8. Estimated Total Cost of Repair (N.M.A.C. 12.2.14.11(H)): ', directions:'DIRECTIONS: Skip until step 8. See below.') 
Section.create(id:4, has_checkbox:true, number:'5', question:'5. Inspection Revealed Safety Issues: ', directions:'DIRECTIONS: For the following, a “yes” and “no” box should be checked for each item. If “yes” is checked, identify the safety issues with particularity (N.M.A.C. 12.2.14.11(I))') 
Section.create(id:5, has_checkbox:true, number:'6', question:'6. Inspection Revealed Frame Damage:', directions:'DIRECTIONS: For the following, a “yes” and “no” box should be checked for each item. If “yes” is checked, identify the frame damage with particularity (N.M.A.C. 12.2.14.11(J))') 
Section.create(id:6, has_checkbox:true, number:'7_1_a', question:'(a) differences in paint color or texture', directions:'') 
Section.create(id:7, has_checkbox:true, number:'7_1_b', question:'(b) mismatched sizes of metallic sparkle in the paint', directions:'') 
Section.create(id:8, has_checkbox:true, number:'7_1_c', question:'(c) embedded dirt or deep scratches in the top coat of the paint', directions:'') 
Section.create(id:9, has_checkbox:true, number:'7_1_d', question:'(d) uneven paint thickness', directions:'') 
Section.create(id:10, has_checkbox:true, number:'7_2_a', question:'(a) uneven gaps between sheet metal panels', directions:'') 
Section.create(id:11, has_checkbox:true, number:'7_2_b', question:'(b) differences between the headlamps', directions:'') 
Section.create(id:12, has_checkbox:true, number:'7_2_c', question:'(c) paint overspray on moldings and trim', directions:'') 
Section.create(id:13, has_checkbox:true, number:'7_2_d', question:'(d) paint tape edges in the jams', directions:'') 
Section.create(id:14, has_checkbox:true, number:'7_2_e', question:'(e) paint chipped off of bolt heads', directions:'') 
Section.create(id:15, has_checkbox:true, number:'7_2_f', question:'(f) paint missing around bolt heads or bolts not centered in the bolt hole', directions:'') 
Section.create(id:16, has_checkbox:true, number:'7_2_g', question:'(g) hammer damage', directions:'') 
Section.create(id:17, has_checkbox:true, number:'7_2_h', question:'(h) holes drilled and plugged in jams or shell of the motor vehicle', directions:'') 
Section.create(id:18, has_checkbox:true, number:'7_2_i', question:'(i) damage inside the trunk or under the spare tire', directions:'') 
Section.create(id:19, has_checkbox:true, number:'7_2_j', question:'(j) signs of corrosion or lack of corrosion protection', directions:'') 
Section.create(id:20, has_checkbox:true, number:'7_3_a', question:'(a) pinched weld flange underneath the motor vehicle', directions:'') 
Section.create(id:21, has_checkbox:true, number:'7_3_b', question:'(b) weld sites', directions:'') 
Section.create(id:22, has_checkbox:true, number:'7_3_c', question:'(c) signs of repair to unibody structural parts', directions:'') 
Section.create(id:23, has_checkbox:true, number:'7_3_d', question:'(d) signs of buckles or non-OEM welding repair to the unibody structural parts', directions:'') 
Section.create(id:24, has_checkbox:true, number:'7_3_e', question:'(e) signs of corrosion or lack of corrosion protection', directions:'') 
Section.create(id:25, has_checkbox:true, number:'7_3_f', question:'(f) signs of any other alteration or repair having been performed to the chassis', directions:'') 
Section.create(id:26, has_checkbox:true, number:'7_3_g', question:'(g) odometer alteration or repair', directions:'') 
Section.create(id:27, has_checkbox:true, number:'7_4', question:'(4) signs of differences and inconsistencies with the motor vehicle’s caulking and seam sealer (N.M.A.C. 12.2.14.11(L)(4))', directions:'') 
Section.create(id:28, has_checkbox:true, number:'7_5', question:'(5) signs of tampering with motor vehicle’s identification tags (N.M.A.C. 12.2.14.11(L)(5))', directions:'') 
Section.create(id:29, has_checkbox:true, number:'7_6', question:'(6) signs of motor vehicle parts labeled “R-DOT” (N.M.A.C. 12.2.14.11(L)(6))', directions:'') 
Section.create(id:30, has_checkbox:true, number:'7_7', question:'(7) signs of any type of repairs not consistent with I-CAR collision repair standards or equivalent (N.M.A.C.12.2.14.11(L)(7))', directions:'') 
Section.create(id:31, has_checkbox:false, number:'8', question:'8. Estimated Total Cost for Repairs and Alterations:', directions:'DIRECTIONS: Above, estimate the total cost of alterations or repairs for this vehicle to be restored to I-Car standards of equivalent industry standards using industry accepted reverse engineering protocols and original equipment manufacturer “OEM” replacement parts; OR flat rate manual costs as indicated by a nationally recognized manual commonly used in the industry of auto repair. (N.M.A.C.12.2.14.7). The total should then be entered in the box above AND the box titled ESTIMATED TOTAL COST OF REPAIR in the first section of this report.') 
Section.create(id:32, has_checkbox:false, number:'9_1', question:'Date of Inspection ', directions:'') 
Section.create(id:33, has_checkbox:false, number:'9_2', question:'Calculation and total cost for inspection', directions:'') 
Section.create(id:34, has_checkbox:false, number:'9_3', question:'Total Cost:', directions:'') 
